site_name: STinteV
site_description: STinteV - a web server for aggregated spatiotemporal omics data visualization.

repo_name: STinteV
repo_url: https://github.com/RainyBlue-w/STinteV

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
- Home: index.md
- Tutorials:
  - Getting started: getting_started.md
  - Data management: data_management.md
  - Plot panels: plot_panels.md
  - Panel linkages: panel_linkages.md
- Examples:
  - Example 1 - 2D visualization: example1_2dVisualization.md
  - Example 2 - 3D visualization: example2_3dVisualization.md

# Document dates
plugins:
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: date

extra:
  homepage: https://stintev.site/