site_name: STinteV
site_description: STinteV - a web server for aggregated spatiotemporal omics data visualization.
theme:
  name: material
nav:
- Home: index.md
- Tutorials:
  - Getting started: getting_started.md
  - Data management: data_management.md
  - Plot panels: plot_panels.md
  - Panel linkages: panel_linkages.md
  - "Example 1: 2D visualization": example1_2dVisualization.md
  - "Example 2: 3D visualization": example2_3dVisualization.md